name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: openssl install
      run: sudo apt-get install libssl-dev
      
    - name: unit test install
      run: sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
      
    - name: make
      run: make
      
    - name: test
      run: ./test/run_all_tests
    
    - name: Doxygen Action
    - uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./docs/Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
